- src/base.css
- src/components/WipHeader.astro
> Small style polishes

- src/pages/showcase.astro
> Fix showcase

- src/pages/showcase.astro
> Fix Showcase errors 2

- astro.config.mjs
> Fix Base URL

- .github/workflows/lint.yml
> Run prettier

- .github/workflows/lint.yml
- .husky/pre-commit
- src/base.css
- src/components/AnimatedCloseButton.astro
- src/components/Button.astro
- src/components/Header.astro
> Run stylelint and add it to CI

- astro.config.mjs
> Fix base path by including it in the site url

- src/components/Address.astro
- src/content/addresses/w2eu.yml
bin mir nicht sicher ob das styling so besser ist:
> print the full address in kit but not flyer and new styling

- src/content/blocks/hide/en.mdx
ab Zeile 8 Ausklappen, Interner Verlinkung zu BAMF Und ZAB (Adresse), Interne Verlinkung zu eidesstattl Versicherung (Vorlage)
> Block HIDE en.mdx

- src/content/pages/forms/en.mdx
ERgänzung: An affidavit is similar to a written witness statement in which you swear to tell the truth. You can use it as proof to the authorities. If you lie, you could face a fine or even imprisonment.
> Affidavit.mdx

- src/content/blocks/fax/en.mdx
Zeile 12 externe Link zu simple fax einbauen
> FAX Test en.mdx

- src/content/blocks/fax/de.mdx
- src/content/blocks/fax/en.mdx
- src/content/pages/contacts/de.mdx
- src/content/pages/contacts/en.mdx
fehlt: EXTERNER LINK ZU simple fax
Absatz bei Kontakte Behörden und Gerichte zu diesem Block machen!
> FAX Text de.mdx

- src/content/flyers/detention/de.mdx
- Stichpunkte am Ende ergänzt (Quelle: Cloud)
- Block "hide" ergänzt
> Abschiebehaft Update de.mdx

- src/content/flyers/detention/en.mdx
- Stichpunkte am Ende ergänzt (analog Cloud)
- Block "hide" ergänzt
> detention Update en.mdx

- src/content/flyers/dublin/de.mdx
> Dublin Update de.mdx

- src/content/flyers/dublin/en.mdx
> Dublin Update en.mdx

- src/content/flyers/ongoing-deportation/en.mdx
Korrektur: am Ende war noch ein Stück rein kopierter deutscher Text
> ongoing deportation Update en.mdx

- src/content/flyers/police/de.mdx
Abschiebemonitoring 2x verlinkt, 1x rausgenommen
> Police Update de.mdx

- src/content/flyers/police/en.mdx
LInk Abschiebemonitoring doppelt, 1x raus
> police Update en.mdx

- src/content/blocks/deportation-danger/de.mdx
> deportation danger Update de.mdx

- src/content/blocks/deportation-protection/de.mdx
> deportation protection Update de.mdx

- src/content/blocks/deportation-danger/en.mdx
> deportation danger Update en.mdx

- src/content/flyers/procedure/de.mdx
> procedure Update de.mdx

- src/content/flyers/procedure/en.mdx
fehlende Übersetzung 
Unterkunft >> accomodation
> procedure Update en.mdx

- src/content/pages/contacts/de.mdx
> kontakte Update de.mdx

- src/content/pages/contacts/en.mdx
> contacts Update en.mdx

- src/content/pages/forms/de.mdx
Adresse Abschiebehaftkontaktgruppe ergänzt
> forms Update de.mdx

- src/content/pages/forms/en.mdx
Adresse Abschiebehaftkontaktgruppe ergänzt
> forms Update en.mdx

- src/content/flyers/duldung/de.mdx
- src/content/flyers/duldung/en.mdx
Duldungslink raus, leichte Kürzungen, kleine Korrekturen
> Kürzungen-de.mdx

- src/content/blocks/kit-procedure-support/en.mdx
> Update en.mdx - kit-procedure-support

- src/content/blocks/kit-ongoing-deportation-support/de.mdx
- src/content/blocks/kit-ongoing-deportation-support/en.mdx
Inhalt aus gekürzten Flyer Laufende Abschiebung
> Ergänzungen de.mdx

- src/content/flyers/police/en.mdx
> Adressen Update en.mdx

- README.md
CC-NC ohne Namensnennung für redaktionellen Inhalt
MIT-NC für Software
> Lizenz update README.md
